version: '3'

services:
  redis-stack:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "8001:8001"

  